### ISSUE TITLE
Identity sign up exception

### ISSUE THREAD

**Issue by onelesd** [ineedthis/phoenix-starter#5]
When attempting to Sign Up (the retro way) an exception occurs:

My .envrc is unchanged from the example .envrc.

```
[error] #PID<0.457.0> running PhoenixStarter.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /auth/identity/callback
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :ets.lookup(:exometer_2, [:phoenix_starter, :ecto, :query_exec_time])
        src/exometer.erl:213: :exometer.update_/2
        (phoenix_starter) lib/phoenix_starter/repo.ex:5: PhoenixStarter.Repo.log/1
        (ecto) lib/ecto/adapters/sql.ex:227: Ecto.Adapters.SQL.query/5
        (ecto) lib/ecto/adapters/sql.ex:183: Ecto.Adapters.SQL.query!/5
        (ecto) lib/ecto/adapters/sql.ex:481: Ecto.Adapters.SQL.execute/6
        (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
        (ecto) lib/ecto/repo/queryable.ex:44: Ecto.Repo.Queryable.one/4
        (phoenix_starter) web/auth/user_from_auth.ex:89: PhoenixStarter.UserFromAuth.auth_and_validate/2
        (phoenix_starter) web/auth/user_from_auth.ex:6: PhoenixStarter.UserFromAuth.get_or_insert/3
        (phoenix_starter) web/controllers/auth_controller.ex:24: PhoenixStarter.AuthController.callback/4
        (phoenix_starter) web/controllers/auth_controller.ex:1: PhoenixStarter.AuthController.action/2
        (phoenix_starter) web/controllers/auth_controller.ex:1: PhoenixStarter.AuthController.phoenix_controller_pipeline/2
        (phoenix_starter) lib/phoenix/router.ex:261: PhoenixStarter.Router.dispatch/2
        (phoenix_starter) web/router.ex:1: PhoenixStarter.Router.do_call/2
        (phoenix_starter) lib/phoenix_starter/endpoint.ex:1: PhoenixStarter.Endpoint.phoenix_pipeline/1
        (phoenix_starter) lib/plug/debugger.ex:93: PhoenixStarter.Endpoint."call (overridable 3)"/2
        (phoenix_starter) lib/phoenix/endpoint/render_errors.ex:34: PhoenixStarter.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
```

**Comment by mjcloutier** [comment]
Hey there, stopped working on this project a while back, and gonna start updating the project again. If still interested in testing out the project, should try pulling down the most recent changes. I removed exometer from the project and gonna drop in a saas solution after so much development in last 6 months in the Elixir/Phoenix community much more options available.
